services:
  k6:
    image: grafana/k6:latest
    networks:
      - k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6:/scripts
    command: run /scripts/test.js

networks:
  k6:
    external: true